step:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag=gcr.io/$GCP_PROJECT_ID/irunning', '--build-arg="VUE_APP_API_KEY=$VUE_APP_API_KEY"', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$GCP_PROJECT_ID/irunning']
   # DEPLOY CONTAINER WITH GCLOUD
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "my-service"
      - "--image=gcr.io/$GCP_PROJECT_ID/irunning
      - "--platform=managed"
      - "--region=us-central1"
      - "--min-instances=1"
      - "--max-instances=3"
      - "--port=80"
    timeout: 180s
images: 
  - "gcr.io/$GCP_PROJECT_ID/irunning"
substitutions:
  VUE_APP_API_KEY: https://irunningapi.bibiota.com/api
