step:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag=asia.gcr.io/$GCP_PROJECT_ID/irunning', '--build-arg="SERVER_CONF=$_SERVER_CONF"', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia.gcr.io/$GCP_PROJECT_ID/irunning']
substitutions:
  VUE_APP_API_KEY: https://irunningapi.bibiota.com/api
