steps:
    # build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'docker build --build-arg=VUE_APP_API_KEY=${VUE_APP_API_KEY}',
      'gcr.io/$PROJECT_ID/irunning',
      '.',
    ]
    # push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/irunning']
    # deploy to gke
  # - name: "gcr.io/cloud-builders/gke-deploy"
  #   args:
  #   - run
  #   - --filename=irunning
  #   - --location=asia-east1
  #   - --cluster=irunning
