steps:
    # build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--build-arg',
      'VUE_APP_API_KEY=$VUE_APP_API_KEY',
      '-t',
      'gcr.io/$GCP_PROJECT_ID/irunning',
      '.',
    ]
    # push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$GCP_PROJECT_ID/irunning']
    # deploy to gke
  # - name: "gcr.io/cloud-builders/gke-deploy"
  #   args:
  #   - run
  #   - --filename=irunning
  #   - --location=asia-east1
  #   - --cluster=irunning
