steps:
- name: node:14
  entrypoint: npm
  args: ["install"]
- name: node:14
  entrypoint: yarn
  args: ["run", "docs:build"]
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
timeout: "1600s"
