steps:
  # build node
  - name: 'node'
    entrypoint: 'npm'
    args: [
      'install'
    ]
  # create env and npm test
  - name: 'node'
    entrypoint: 'npm'
    args: [
      'run', 'test:unit'
    ]
    env:
    - 'VUE_APP_API_KEY=$_VUE_APP_API_KEY'
    - 'VUE_APP_NODE_API_KEY=$_VUE_APP_NODE_API_KEY'
    - 'VUE_APP_API_KEY=$_VUE_APP_API_KEY'
    - 'VUE_APP_API_STORAGE=$_VUE_APP_API_STORAGE'
    - 'VUE_APP_STRAVA_CLIENT_ID=$_VUE_APP_STRAVA_CLIENT_ID'
    - 'VUE_APP_STRAVA_CLIENT_SECRET=$_VUE_APP_STRAVA_CLIENT_SECRET'
    - 'VUE_APP_REDIRECT_URI=$_VUE_APP_REDIRECT_URI'
    - 'BASE_URL=$_BASE_URL'
    - 'VUE_APP_ENV=$_VUE_APP_ENV'
    - 'VUE_APP_GAPI=$_VUE_APP_GAPI'
    # build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--build-arg',
      'VUE_APP_API_KEY=$_VUE_APP_API_KEY',
      '--build-arg',
      'VUE_APP_NODE_API_KEY=$_VUE_APP_NODE_API_KEY',
      '--build-arg',
      'VUE_APP_API_STORAGE=$_VUE_APP_API_STORAGE',
      '--build-arg',
      'VUE_APP_STRAVA_CLIENT_ID=$_VUE_APP_STRAVA_CLIENT_ID',
      '--build-arg',
      'VUE_APP_STRAVA_CLIENT_SECRET=$_VUE_APP_STRAVA_CLIENT_SECRET',
      '--build-arg',
      'VUE_APP_REDIRECT_URI=$_VUE_APP_REDIRECT_URI',
      '--build-arg',
      'BASE_URL=$_BASE_URL',
      '--build-arg',
      'VUE_APP_ENV=$_VUE_APP_ENV',
      '--build-arg',
      'VUE_APP_GAPI=$_VUE_APP_GAPI',
      '-t',
      'gcr.io/$_GCP_PROJECT_ID/${_IMAGE}:$BUILD_ID',
      '.',
    ]
    # push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$_GCP_PROJECT_ID/${_IMAGE}:$BUILD_ID']
    # deploy to gke
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
    - 'set'
    - 'image'
    - 'deployment'
    - '${_DEPLOYMENT}'
    - '${_CONTAINER}=gcr.io/$_GCP_PROJECT_ID/${_IMAGE}:$BUILD_ID'
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER}'
