steps:
    # build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/irunning', '.' ]
    # push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/irunning']
    # deploy to gke
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
    - run
    - --filename=irunning
    - --location=asia-east2
    - --cluster=irunning