steps:
    # build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--build-arg',
      'VUE_APP_API_KEY=$_VUE_APP_API_KEY',
      '--build-arg',
      'VUE_APP_NODE_API_KEY=$_VUE_APP_NODE_API_KEY',
      '--build-arg',
      'VUE_APP_API_STORAGE=$_VUE_APP_API_STORAGE',
      '--build-arg',
      'VUE_APP_STRAVA_CLIENT_ID=$_VUE_APP_STRAVA_CLIENT_ID',
      '--build-arg',
      'VUE_APP_STRAVA_CLIENT_SECRET=$_VUE_APP_STRAVA_CLIENT_SECRET',
      '--build-arg',
      'VUE_APP_REDIRECT_URI=$_VUE_APP_REDIRECT_URI',
      '--build-arg',
      'BASE_URL=$_BASE_URL',
      '--build-arg',
      'VUE_APP_ENV=$_VUE_APP_ENV',
      '--build-arg',
      'VUE_APP_GAPI=$_VUE_APP_GAPI',
      '-t',
      'gcr.io/$GCP_PROJECT_ID/irunning',
      '.',
    ]
    # push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$GCP_PROJECT_ID/irunning']
    # deploy to gke
  # - name: "gcr.io/cloud-builders/gke-deploy"
  #   args:
  #   - run
  #   - --filename=irunning
  #   - --location=asia-east1
  #   - --cluster=irunning
