apiVersion: apps/v1
kind: Deployment
metadata:
  name: irunning-deployment
  labels:
    app: irunning
spec:
  replicas: 2
  selector:
    matchLabels:
      app: irunning
  template:
    metadata:
      labels:
        app: irunning
    spec:
      containers:
      - name: irunning
        image: asia.gcr.io/irunning-324312/irunning:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 216Mi
          limits:
            cpu: 100m
            memory: 216Mi

