#!/bin/bash
# VUE APP
echo VUE_APP_API_KEY=$VUE_APP_API_KEY >> .env

echo VUE_APP_STRAVA_CLIENT_ID=$VUE_APP_STRAVA_CLIENT_ID >> .env
echo VUE_APP_STRAVA_CLIENT_SECRET=$VUE_APP_STRAVA_CLIENT_SECRET >> .env
