#!/bin/sh

echo VUE_APP_API_KEY=$VUE_APP_API_KEY >> .env
echo VUE_APP_NODE_API_KEY=$VUE_APP_NODE_API_KEY >> .env
echo VUE_APP_API_STORAGE=$VUE_APP_API_STORAGE >> .env
echo VUE_APP_STRAVA_CLIENT_ID=$VUE_APP_STRAVA_CLIENT_ID >> .env
echo VUE_APP_STRAVA_CLIENT_SECRET=$VUE_APP_STRAVA_CLIENT_SECRET >> .env
echo VUE_APP_REDIRECT_URI=$VUE_APP_REDIRECT_URI >> .env
echo BASE_URL=$BASE_URL >> .env
echo VUE_APP_ENV=$VUE_APP_ENV >> .env
echo VUE_APP_GAPI=$VUE_APP_GAPI >>  .env
echo VUE_APP_GCLIENT_ID=$VUE_APP_GCLIENT_ID >>  .env